export const ErrorCodes = {
  COMMON_VALIDATION: 'common.validation',
  AGENT_TOKEN_INVALID: 'agent.token_invalid',
  AGENT_TOKEN_EXPIRED: 'agent.token_expired',
  AGENT_FORBIDDEN: 'agent.forbidden',
  AGENT_SCOPE_DENIED: 'agent.scope_denied',
  AGENT_POLICY_DENIED: 'agent.policy_denied',
  AGENT_ACTION_UNKNOWN: 'agent.action_unknown',
  AGENT_ACTION_INVALID: 'agent.action_invalid',
  AGENT_DRAFT_NOT_FOUND: 'agent.draft_not_found',
  AGENT_DRAFT_ALREADY_FINAL: 'agent.draft_already_final',
  AGENT_PREFLIGHT_REQUIRED: 'agent.preflight_required',
  AGENT_PREFLIGHT_MISMATCH: 'agent.preflight_mismatch',
  AGENT_PREFLIGHT_NOT_FOUND: 'agent.preflight_not_found',
  AGENT_PRECONDITION_FAILED: 'agent.precondition_failed',
  AGENT_IDEMPOTENCY_REQUIRED: 'agent.idempotency_required',
  AGENT_IDEMPOTENCY_REPLAY: 'agent.idempotency_replay',
  AGENT_AUTO_EXECUTE_DISABLED: 'agent.auto_execute_disabled',
  AGENT_AUTO_EXECUTE_DENIED: 'agent.auto_execute_denied',
  AGENT_AUTO_EXECUTE_EXPIRED: 'agent.auto_execute_expired',
  AGENT_STEP_UP_REQUIRED: 'agent.step_up_required',
  AGENT_STEP_UP_INVALID: 'agent.step_up_invalid',
  AGENT_RATE_LIMITED: 'agent.rate_limited',
  AGENT_EXECUTION_FAILED: 'agent.execution_failed',
  AGENT_INTENT_NOT_FOUND: 'agent.intent_not_found',
  AGENT_INTENT_EXPIRED: 'agent.intent_expired',
  AGENT_INTENT_LOW_CONFIDENCE: 'agent.intent_low_confidence',
  AGENT_INTENT_CONFLICTING: 'agent.intent_conflicting',
  AGENT_INTENT_TOOL_MISMATCH: 'agent.intent_tool_mismatch',
  AGENT_INTENT_PAYLOAD_EXCEEDS_BOUND: 'agent.intent_payload_exceeds_bound',
  AGENT_INTENT_REVIEW_REQUIRED: 'agent.intent_review_required',
  AGENT_CONTEXT_RISK_HIGH: 'agent.context_risk_high',
  AGENT_CONTEXT_TOOL_HIDDEN: 'agent.context_tool_hidden',
  AGENT_CONTEXT_MODE_DOWNGRADED: 'agent.context_mode_downgraded',
  AGENT_CONTEXT_MANIFEST_STALE: 'agent.context_manifest_stale',
  AGENT_CONTEXT_SNAPSHOT_EXPIRED: 'agent.context_snapshot_expired',
  AGENT_CONTEXT_SNAPSHOT_CROSS_KEY: 'agent.context_snapshot_cross_key',
  AGENT_CONTEXT_SNAPSHOT_NOT_FOUND: 'agent.context_snapshot_not_found',
  AGENT_CONTEXT_PROVENANCE_MISSING: 'agent.context_provenance_missing',
  AGENT_CONTEXT_AUDIT_REDACTED: 'agent.context_audit_redacted',
  AGENT_NOT_FOUND: 'agent.not_found'
} as const

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes]
